language: node_js

node_js:
  - "10"
  - "8"

script:
  - yarn test

branches:
  only:
    - master

after_success:
  - npm run semantic-release
  - bash <(curl -s https://codecov.io/bash)

cache: yarn
